name: prebuild

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - name: darwin
            os: macos-latest
            node: x64
          - name: win32-x86
            os: windows-2019
            node: x86
          - name: win32-x64
            os: windows-2019
            node: x64
          - name: linux-x64
            os: ubuntu-latest
            node: x64
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          architecture: ${{ matrix.node }}

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - run: npm install
      - run: npm run prebuild-${{ matrix.name }}
      - run: tar -zcvf ${{ matrix.name }}.tar.gz -C prebuilds .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.tar.gz
          retention-days: 1

  release:
    name: Release
    needs: prebuild
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - uses: docker://antonyurchenko/git-release:v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: artifacts/*/*.tar.gz
